FastFood/FastFood/Models/FoodsViewModel.cs
using FastFood.Data.Models;

namespace FastFood.Models
{
    public class FoodsViewModel
    {
        public IEnumerable<Food> Foods { get; set; } = null!;
        public string CurrentCategory { get; set; }=null!;
    }
}

FastFood/FastFood/Controllers/FoodController.cs
using FastFood.Contracts;
using FastFood.Data.Models;
using FastFood.Models;
using Microsoft.AspNetCore.Mvc;

namespace FastFood.Controllers
{
    public class FoodController:Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IFoodService foodService;

        public FoodController(ICategoryService categoryService, IFoodService foodService)
        {
            this.categoryService = categoryService;
            this.foodService = foodService;
        }

        public IActionResult All(FoodsViewModel model,string category)
        {
            string _category = category;
            IEnumerable<Food> foods;


            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                foods = foodService.Foods.OrderBy(f => f.Id);
                currentCategory = "All foods";
            }
            else
            {
                if (string.Equals("Vegetarian", _category,StringComparison.OrdinalIgnoreCase))
                {
                    currentCategory = "Vegetarian";
                    foods = foodService.Foods.Where(f => f.Category?.CategoryName==currentCategory).OrderBy(f => f.Name);
                }
                else
                {
                    currentCategory = "Non-Vegetarian";
                    foods = foodService.Foods.Where(f => f.Category?.CategoryName==currentCategory).OrderBy(f => f.Name);
                }
                currentCategory = _category;
            }


            model = new FoodsViewModel
            {
                Foods = foods,
                CurrentCategory = currentCategory
            };
           
            return View(model);
        }

        public ViewResult Search(FoodsViewModel model,string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Food> foods;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                foods = foodService.Foods.OrderBy(f => f.Id);
            }
            else
            {
                foods = foodService.Foods.Where(f => f.Name.ToLower().StartsWith(_searchString.ToLower()));
            }

            return View("~/Views/Food/All.cshtml", new FoodsViewModel { Foods = foods, CurrentCategory = "All foods" });
        }

        public ViewResult Details(int foodId)
        {
            var food = foodService.Foods.FirstOrDefault(f => f.Id == foodId);
            if (food == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(food);
        }
    }
}

FastFood/FastFood/Controllers/ShoppingCartController.cs
using FastFood.Contracts;
using FastFood.Data.Models;
using FastFood.Models;
using FastFood.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FastFood.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IFoodService foodService;
        private readonly ShoppingCart shoppingCart;
        public ShoppingCartController(IFoodService foodService, ShoppingCart shoppingCart)
        {
            this.foodService=foodService;
            this.shoppingCart=shoppingCart;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var items = shoppingCart.GetShoppingCartItems();
            shoppingCart.Items= items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart=shoppingCart,
                ShoppingCartTotal=shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }
        [Authorize]
        public IActionResult AddToShoppingCart(int foodId)
        {
            var selectedFood=foodService.Foods.FirstOrDefault(f=>f.Id==foodId);

            if (selectedFood != null)
            {
                shoppingCart.AddToCart(selectedFood, 1);
            }

            return RedirectToAction("Index","Home");
        }


        
        public IActionResult RemoveFromShoppingCart(int foodId)
        {

            var selectedFood = foodService.Foods.FirstOrDefault(f => f.Id == foodId);

            if (selectedFood != null)
            {
                shoppingCart.RemoveFromCart(selectedFood);
            } 
            
            return RedirectToAction("Index","Home");
        }

    }
}

FastFood/FastFood/Views/Food/All.cshtml
@model FoodsViewModel

<div class="row marginTop">
    @foreach (var food in Model.Foods)
    {
        <partial name="/Views/Shared/_FoodSummary.cshtml" for="@food"/>
    }
</div>

FastFood/FastFood/Views/Food/Details.cshtml
@model Food
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

<div class="container marginTop">
    <div class="row">
        <div class="card">
            <div class="text-center view overlay hm-white-slight">
                <img src="@Model.ImageUrl" class="img-fluid">
                <a href="#">
                    <div class="mask waves-effect waves-light"></div>
                </a>
            </div>
            <div class="card-block">
                
                <h4 class="card-title">@Model.Name</h4>
                
                <p class="card-text">@Model.LongDescription.</p>
                <p class="btn btn-group pull-right">
                    <a asp-controller="Food" asp-action="All" class="btn btn-default">Show all foods</a>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart">
                        Add @Model.Name to cart
                    </a>
                    }
                    
                </p>
            </div>
        </div>
    </div>
</div>