FastFood/FastFood/Models/ShoppingCartViewModel.cs
using FastFood.Data.Models;

namespace FastFood.Models
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; } = null!;

        public decimal ShoppingCartTotal { get; set; }
    }
}

FastFood/FastFood/Controllers/FoodController.cs
using FastFood.Contracts;
using FastFood.Data.Models;
using FastFood.Models;
using Microsoft.AspNetCore.Mvc;

namespace FastFood.Controllers
{
    public class FoodController:Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IFoodService foodService;

        public FoodController(ICategoryService categoryService, IFoodService foodService)
        {
            this.categoryService = categoryService;
            this.foodService = foodService;
        }

        public IActionResult All(FoodsViewModel model,string category)
        {
            string _category = category;
            IEnumerable<Food> foods;


            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                foods = foodService.Foods.OrderBy(f => f.Id);
                currentCategory = "All foods";
            }
            else
            {
                if (string.Equals("Vegetarian", _category,StringComparison.OrdinalIgnoreCase))
                {
                    currentCategory = "Vegetarian";
                    foods = foodService.Foods.Where(f => f.Category?.CategoryName==currentCategory).OrderBy(f => f.Name);
                }
                else
                {
                    currentCategory = "Non-Vegetarian";
                    foods = foodService.Foods.Where(f => f.Category?.CategoryName==currentCategory).OrderBy(f => f.Name);
                }
                currentCategory = _category;
            }


            model = new FoodsViewModel
            {
                Foods = foods,
                CurrentCategory = currentCategory
            };
           
            return View(model);
        }

        public ViewResult Search(FoodsViewModel model,string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Food> foods;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                foods = foodService.Foods.OrderBy(f => f.Id);
            }
            else
            {
                foods = foodService.Foods.Where(f => f.Name.ToLower().StartsWith(_searchString.ToLower()));
            }

            return View("~/Views/Food/All.cshtml", new FoodsViewModel { Foods = foods, CurrentCategory = "All foods" });
        }

        public ViewResult Details(int foodId)
        {
            var food = foodService.Foods.FirstOrDefault(f => f.Id == foodId);
            if (food == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(food);
        }
    }
}

FastFood/FastFood/Controllers/OrderController.cs
using FastFood.Contracts;
using FastFood.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FastFood.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService service;

        private readonly ShoppingCart shoppingCart;

        public OrderController(IOrderService service, ShoppingCart shoppingCart)
        {
            this.service = service;
            this.shoppingCart = shoppingCart;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Order order)
        {
            var items = shoppingCart.GetShoppingCartItems();
            shoppingCart.Items = items;

            if(shoppingCart.Items.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some foods first.");
            }
            if (ModelState.IsValid)
            {
                service.CreateOrder(order);
                shoppingCart.ClearCard();

                return RedirectToAction("CheckoutComplete");
            }
            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order!";
            return View();
        }

    }
}

FastFood/FastFood/Controllers/ShoppingCartController.cs
using FastFood.Contracts;
using FastFood.Data.Models;
using FastFood.Models;
using FastFood.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FastFood.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IFoodService foodService;
        private readonly ShoppingCart shoppingCart;
        public ShoppingCartController(IFoodService foodService, ShoppingCart shoppingCart)
        {
            this.foodService=foodService;
            this.shoppingCart=shoppingCart;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var items = shoppingCart.GetShoppingCartItems();
            shoppingCart.Items= items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart=shoppingCart,
                ShoppingCartTotal=shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }
        [Authorize]
        public IActionResult AddToShoppingCart(int foodId)
        {
            var selectedFood=foodService.Foods.FirstOrDefault(f=>f.Id==foodId);

            if (selectedFood != null)
            {
                shoppingCart.AddToCart(selectedFood, 1);
            }

            return RedirectToAction("Index","Home");
        }


        
        public IActionResult RemoveFromShoppingCart(int foodId)
        {

            var selectedFood = foodService.Foods.FirstOrDefault(f => f.Id == foodId);

            if (selectedFood != null)
            {
                shoppingCart.RemoveFromCart(selectedFood);
            } 
            
            return RedirectToAction("Index","Home");
        }

    }
}

FastFood/FastFood/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<div class="row checkoutForm">
    <h2>Your shopping cart</h2>
    <h4>Here are the foods in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Food</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.Items.Where(s => s.IsDeleted == false))
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Food.Name</td>
                    <td class="text-right">@line.Food.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Food.Price).ToString("c"))
                    </td>
                   
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            @*
            <a class="btn-group">
                <p class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more foods<span class="caret"></span>
                </p>
                <ul class="dropdown-menu" role="menu">
                 @foreach (var category in Model.ShoppingCart.Items)
                {
                 <li>
                   <a asp-controller="Food" asp-action="All"
                   asp-route-category="@category?.Food?.Category?.CategoryName">@category?.Food?.Category?.CategoryName</a>
               </li>
                }
                </ul>
            </a>
            *@
        </div>
    </div>
</div>